# [[redirects]]
#   from = "/*"
#   to = "/"
#   status = 200

[[redirects]]
from = "https://ita-artem.netlify.app/*"
to = "https://www.saibel.cz/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.ita-artem.netlify.app/*"
to = "https://www.saibel.cz/:splat"
status = 301
force = true